import { QUERY_COMMON } from "src/const/QUERY_CONST";

// SQL 에러 상위 항목 개수
export const TOP_SQL_ERROR_NUMBER = 5;

export const TPS_CAHRT = {
	DATA_NUMS_BY_1_MIN: 12,
	MAX_DATA_NUMBER: 60,
	INTERVAL_SEC: QUERY_COMMON.REFETCH_INTERVAL / 1000,
};

export const AVG_RESPONSE_TIME_CAHRT = {
	DATA_NUMS_BY_1_MIN: 12,
	MAX_DATA_NUMBER: 60,
	INTERVAL_SEC: QUERY_COMMON.REFETCH_INTERVAL / 1000,
};

export const CALL_BIAS_SECONDS = -20;

export const MAX_RETRY_API_QUEUE_ITEM = 3;
